language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
before_install:
  - npm install -g yarn codecov
install:
  - yarn install
before_script:
  - yarn build
script:
  - yarn audit
  - yarn lint
  - yarn test
  - codecov
  - cd test-e2e && npm install && npm test
